# Generated by Django 2.2.16 on 2022-09-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked',
            field=models.CharField(choices=[('b', 'Block'), ('u', 'Unblock')], default='Unblock', max_length=10, verbose_name='Блокировка'),
        ),
    ]
